name: Continuous Integration Workflow

on: [push]

jobs:
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: multi.ootmm.com
        username: ci
        key: ${{ secrets.SSH_KEY_PRIVATE }}
        script: ./deploy-multiserver.sh
